name: Build automation image
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    uses: EENCloud/workflow-library/.github/workflows/build_docker_image.yml@main
    with:
      project-name: "ui-automation"
      app-version: "${{ github.head_ref }}-${{ github.sha }}"
      artifacts-push: true
    secrets:
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      VAULT_CA_CERT: ${{ secrets.VAULT_CA_CERT }}
