name: Build automation image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  set-app-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.set-version.outputs.app_version }}
    steps:
      - name: Set app-version
        id: set-version
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "app_version=latest" >> $GITHUB_OUTPUT
            echo "App version set to 'latest'"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            pr_number=${{ github.event.pull_request.number }}
            echo "app_version=pr-${pr_number}" >> $GITHUB_OUTPUT
            echo "App version set to 'pr-${pr_number}'"
          else
            app_version=${{ github.ref_name }}
            echo "app_version=${app_version}" >> $GITHUB_OUTPUT
            echo "App version set to '${app_version}'"
          fi
          
      - name: Print app_version
        run: echo "The app_version is ${{ steps.set-version.outputs.app_version }}"


