name: Build automation image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  set-app-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.set-version.outputs.app_version }}
    steps:
      - name: Set app-version
        id: set-version
        run: |
          app_version="${{ github.event_name == 'push' && 'latest' || '${GITHUB_REF_NAME}-${GITHUB_SHA}}'}}"
          echo "app_version=${app_version}" >> $GITHUB_OUTPUT
          echo "App version set to '${app_version}'"
      - name: Print app_version
        run: echo "The app_version is ${{ steps.set-version.outputs.app_version }}"
