name: Build automation image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  set-app-version:
    runs-on:
      group: "${{ vars.RUNNER_GROUP }}"
    outputs:
      app_version: ${{ steps.set-version.outputs.app_version }}
    steps:
      - name: Set app-version
        id: set-version
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "app_version=latest" >> $GITHUB_OUTPUT
            echo "App version set to 'latest'"
          else
            app_version="${GITHUB_REF_NAME}-${GITHUB_SHA}"
            echo "app_version=${app_version}" >> $GITHUB_OUTPUT
            echo "App version set to '${app_version}'"
          fi
